const puppeteer = require('puppeteer');
const fs = require('fs');
const path = require('path');

const data = {
  companyName: "Microsoft",
  website: "https://microsoft.com",
  phone: "Not publicly listed",
  address: "One Microsoft Way, Redmond, WA 98052",
  summary: "Microsoft is a multinational technology corporation which produces computer software, consumer electronics, personal computers, and related services.",
  targetAudience: "Global consumers and enterprise businesses.",
  products: [
    { name: "Windows", description: "Operating system for personal computers." },
    { name: "Azure", description: "Cloud computing platform and services." }
  ],
  painPoints: [
    { topic: "Security", explanation: "Continuous need to patch vulnerabilities across a vast ecosystem." }
  ],
  competitors: [
    { name: "Apple", website: "apple.com", reason: "Competes in OS and hardware." }
  ]
};

const htmlContent = `
  <!DOCTYPE html>
  <html>
  <head>
    <style>
      body { font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; color: #333; margin: 0; padding: 20px; background: #fff; }
      .header { text-align: left; margin-bottom: 40px; border-bottom: 2px solid #eee; padding-bottom: 20px; }
      .subtitle { font-size: 12px; font-weight: bold; color: #888; letter-spacing: 1px; margin-bottom: 8px; }
      .title { font-size: 32px; font-weight: 800; color: #111; margin: 0; }
      h2 { font-size: 16px; font-weight: bold; color: #555; text-transform: uppercase; margin-top: 30px; margin-bottom: 12px; letter-spacing: 1px; border-bottom: 1px solid #eee; padding-bottom: 5px; }
      table { width: 100%; border-collapse: collapse; margin-bottom: 20px; }
      td, th { padding: 10px; border-bottom: 1px solid #eee; text-align: left; font-size: 14px; }
      th { background: #f9f9f9; font-weight: bold; color: #555; }
      .label { width: 120px; font-weight: bold; color: #666; }
      p { font-size: 14px; line-height: 1.6; color: #444; margin-bottom: 20px; }
      .list-item { margin-bottom: 15px; page-break-inside: avoid; }
      .list-title { font-weight: bold; font-size: 14px; color: #222; margin-bottom: 4px; }
      .list-desc { font-size: 13px; color: #555; line-height: 1.5; }
      .footer { margin-top: 50px; font-size: 11px; color: #aaa; text-align: center; border-top: 1px solid #eee; padding-top: 20px; }
      a { color: #0066cc; text-decoration: none; }
    </style>
  </head>
  <body>
    <div class="header">
      <div class="subtitle">COMPANY RESEARCH REPORT</div>
      <h1 class="title">${data.companyName}</h1>
    </div>

    <h2>Company Information</h2>
    <table>
      <tr><td class="label">Website</td><td><a href="${data.website}">${data.website}</a></td></tr>
      <tr><td class="label">Phone</td><td>${data.phone || 'Not publicly listed'}</td></tr>
      <tr><td class="label">Address</td><td>${data.address || 'Not publicly listed'}</td></tr>
    </table>

    <h2>Company Summary</h2>
    <p>${data.summary || 'Information unavailable'}</p>

    <h2>Target Audience / Market</h2>
    <p>${data.targetAudience || 'Information unavailable'}</p>

    <h2>Products & Services</h2>
    <div>
      ${(data.products || []).map(p => `
        <div class="list-item">
          <div class="list-title">&bull; ${typeof p === 'string' ? p : p.name}</div>
          ${p.description ? `<div class="list-desc">${p.description}</div>` : ''}
        </div>
      `).join('')}
    </div>

    <h2>AI-Generated Pain Points</h2>
    <div>
      ${(data.painPoints || []).map(p => `
        <div class="list-item">
          <div class="list-title">&bull; ${typeof p === 'string' ? p : p.topic}</div>
          ${p.explanation ? `<div class="list-desc">${p.explanation}</div>` : ''}
        </div>
      `).join('')}
    </div>

    <h2>Competitor Analysis</h2>
    <table>
      <thead>
        <tr><th>Company Name</th><th>Website</th><th>AI Reasoning</th></tr>
      </thead>
      <tbody>
        ${(data.competitors || []).map(c => `
          <tr style="page-break-inside: avoid;">
            <td><strong>${c.name}</strong></td>
            <td><a href="${c.website}">${c.website}</a></td>
            <td>${c.reason || 'Information unavailable'}</td>
          </tr>
        `).join('')}
      </tbody>
    </table>

    <div class="footer">
      Generated by AI Research Assistant &middot; ${new Date().toLocaleDateString('en-US', { month: '2-digit', day: '2-digit', year: 'numeric' })}
    </div>
  </body>
  </html>
`;

(async () => {
  const browser = await puppeteer.launch({
    headless: true,
    args: ['--no-sandbox', '--disable-setuid-sandbox']
  });
  
  const page = await browser.newPage();
  await page.setContent(htmlContent, { waitUntil: 'networkidle0' });
  
  const pdfBuffer = await page.pdf({
    format: 'Letter',
    margin: { top: '0.5in', right: '0.5in', bottom: '0.5in', left: '0.5in' },
    printBackground: true
  });
  
  await browser.close();

  const outDir = path.join(__dirname, 'outputs');
  if (!fs.existsSync(outDir)) {
    fs.mkdirSync(outDir);
  }
  
  fs.writeFileSync(path.join(outDir, 'Microsoft_Report_Raw.pdf'), pdfBuffer);
  console.log('Saved Microsoft_Report_Raw.pdf natively using Puppeteer buffer.');
})();
